//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPrzychodnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int Id_pacjenta { get; set; }
        public string Miasto { get; set; }
        public string ulica { get; set; }
        public string nr_domu_mieszkania { get; set; }
    
        public virtual Pacjent Pacjent { get; set; }
    }
}
