//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPrzychodnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class dawkowanie
    {
        public int Id_dawkowanie { get; set; }
        public Nullable<System.DateTime> Od_kiedy { get; set; }
        public Nullable<System.DateTime> Do_kiedy { get; set; }
        public Nullable<int> ilość_dziennie { get; set; }
        public string Komentarz { get; set; }
        public int Id_diagnozy { get; set; }
        public Nullable<int> Id_lekarstwa { get; set; }
    
        public virtual Diagnoza Diagnoza { get; set; }
        public virtual Lekarstwa Lekarstwa { get; set; }
    }
}
