//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPrzychodnia
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Text.RegularExpressions;

    public partial class Pacjent 
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacjent()
        {
            this.Wizyta = new HashSet<Wizyta>();
        }
    
        public int Id_pacjenta { get; set; }
        public string Imie { get; set; }
        public string nazwisko { get; set; }
        public string Pesel { get; set; }
    
       internal virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Wizyta> Wizyta { get; set; }
       //public string Error { get; set; }
       


       // public string this[string nazwa]
       // {
       //     get
       //     {
       //         string komunikat = string.Empty;
       //         switch(nazwa)
       //         {
       //             case "Pesel":
       //                 if (string.IsNullOrEmpty(Pesel))
       //                     komunikat = "Pesel musi byæ wpisany!";
       //                 else if (!Regex.IsMatch(Pesel, @"^\d{11}$"))
       //                     komunikat = "Numer Pesel musi mieæ 11 znaków";
       //                 break;
       //         };
       //         return komunikat;
       //     }
       // }
    }
}
